# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
import torch

print(torch.cuda.is_available())

print(torch.cuda.memory_allocated(0))
print(torch.cuda.max_memory_allocated(0))
print(torch.cuda.max_memory_reserved(0))


True
0
0
0


### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
tensor = torch.rand((7,7))

# Create random tensor
print(tensor)


tensor([[0.5891, 0.7451, 0.1286, 0.7497, 0.4608, 0.8600, 0.5526],
        [0.2108, 0.2836, 0.1102, 0.9344, 0.8887, 0.3066, 0.0584],
        [0.4793, 0.7788, 0.6512, 0.2813, 0.9474, 0.6629, 0.3927],
        [0.8428, 0.9245, 0.0206, 0.0491, 0.4456, 0.4537, 0.3868],
        [0.4712, 0.0038, 0.6478, 0.0416, 0.6474, 0.1128, 0.5719],
        [0.7841, 0.3297, 0.9904, 0.2970, 0.1263, 0.4811, 0.8694],
        [0.8522, 0.9026, 0.0462, 0.6373, 0.5365, 0.7597, 0.9622]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor2 = torch.rand((1,7))
print(tensor2)

# Perform matrix multiplication 
tensor3 = tensor * tensor2.T
print(tensor3)

tensor3 = torch.matmul(tensor, tensor2.T)
print(tensor3)

tensor([[0.4854, 0.2511, 0.8072, 0.5402, 0.9435, 0.2107, 0.6801]])
tensor([[0.2859, 0.3616, 0.0624, 0.3639, 0.2236, 0.4174, 0.2682],
        [0.0529, 0.0712, 0.0277, 0.2347, 0.2232, 0.0770, 0.0147],
        [0.3869, 0.6286, 0.5257, 0.2271, 0.7647, 0.5351, 0.3170],
        [0.4553, 0.4995, 0.0111, 0.0265, 0.2407, 0.2451, 0.2090],
        [0.4446, 0.0036, 0.6112, 0.0393, 0.6108, 0.1064, 0.5396],
        [0.1652, 0.0695, 0.2086, 0.0626, 0.0266, 0.1014, 0.1832],
        [0.5796, 0.6139, 0.0314, 0.4335, 0.3649, 0.5167, 0.6544]])
tensor([[1.9737],
        [1.7101],
        [2.4064],
        [1.4636],
        [1.7986],
        [2.2351],
        [2.3425]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(size=(7,7))
y = torch.rand(size=(7,1))

# Matrix multiply tensors
z = torch.matmul(x,y)
print(z)
print(z.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"device: {device}")

# Create two random tensors on GPU
x = torch.rand(size=(2,3)).to(device)
y = torch.rand(size=(2,3)).to(device)
x,y

device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
z = torch.matmul(x,y.T)
z

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
ma = torch.max(z)
print(ma)
# Find min
mi = torch.min(z)
print(mi)

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [15]:
# Find arg max
argmax = torch.argmax(z)

# Find arg min
argmin = torch.argmin(z)

argmax, argmin

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [16]:
# Set seed
torch.manual_seed(7)

# Create random tensor
X = torch.rand(size=(1,1,1,10))

# Remove single dimensions
Y = torch.squeeze(X)

# Print out tensors and their shapes
print(X, X.shape)
print(Y, Y.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
