In [58]:
!nvidia-smi

Tue Feb 27 21:13:21 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.61                 Driver Version: 551.61         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   63C    P2             58W /   60W |    1876MiB /   6144MiB |    100%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [59]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

torch.__version__

'2.2.1+cu121'

In [60]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [61]:
scalar.ndim

0

In [62]:
scalar.item()

7

In [63]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [64]:
vector.ndim

1

In [65]:
vector.shape

torch.Size([2])

In [66]:
MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [67]:
MATRIX.ndim

2

In [68]:
MATRIX.shape

torch.Size([2, 2])

In [69]:
MATRIX[1]

tensor([3, 4])

In [70]:
TENSOR = torch.tensor([[[1,2,3],
                         [2,3,4]]])

In [71]:
TENSOR


tensor([[[1, 2, 3],
         [2, 3, 4]]])

In [72]:
TENSOR.ndim

3

In [73]:
TENSOR.shape

torch.Size([1, 2, 3])

In [74]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [75]:
one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [76]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
RAND = torch.rand(3,4)
RAND

tensor([[0.1235, 0.4972, 0.1272, 0.2725],
        [0.6502, 0.1724, 0.6201, 0.8243],
        [0.3979, 0.9549, 0.9180, 0.0780]])

In [78]:
RAND.dtype

torch.float32

In [79]:
RAND = torch.rand(3,4, dtype=torch.float16)
RAND.dtype

torch.float16

In [80]:
RAND

tensor([[0.1006, 0.3525, 0.6299, 0.7822],
        [0.0874, 0.8857, 0.4863, 0.3643],
        [0.4229, 0.9272, 0.0610, 0.0825]], dtype=torch.float16)

In [81]:
TEST = torch.tensor([3,6,-1], dtype=torch.float16, device="cpu", requires_grad=False)

In [82]:
TEST

tensor([ 3.,  6., -1.], dtype=torch.float16)

In [83]:
TEST32 = TEST.type(torch.int)

In [84]:
TEST32

tensor([ 3,  6, -1], dtype=torch.int32)

In [85]:
TEST*TEST32

tensor([ 9., 36.,  1.], dtype=torch.float16)

In [86]:
TEST.dtype

torch.float16

In [87]:
TEST.shape

torch.Size([3])

In [88]:
TEST.ndim

1

In [89]:
TEST.device

device(type='cpu')

In [90]:
TEST.size()

torch.Size([3])

In [91]:
TEST / TEST32

tensor([1., 1., 1.], dtype=torch.float16)

In [92]:
TEST = torch.tensor([[1,2],[3,4]], dtype=torch.float16)
TEST32 = torch.tensor([[5,6]], dtype=torch.float16)

In [93]:
TEST32

tensor([[5., 6.]], dtype=torch.float16)

In [94]:
torch.mm(TEST, TEST32.T)

tensor([[17.],
        [39.]], dtype=torch.float16)

In [96]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

tensor_A * tensor_B

tensor([[ 7., 20.],
        [24., 44.],
        [45., 72.]])

In [98]:
tensor_A.min()

tensor(1.)

In [99]:
tensor_A.mean()

tensor(3.5000)

In [100]:
tensor_A.sum()

tensor(21.)

In [101]:
tensor_A.argmin()

tensor(0)

In [102]:
tensor_A.argmax()

tensor(5)

In [105]:
tensor_A[0][1]

tensor(2.)

In [107]:
tensor_A.size()

torch.Size([3, 2])

In [108]:
tensor_A_reshape = tensor_A.reshape(2,3)


In [109]:
tensor_A_reshape

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [112]:
x = tensor_A_reshape.view(3,2)

In [113]:
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [114]:
x[0][0] = 10


In [115]:
x

tensor([[10.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]])

In [116]:
tensor_A_reshape

tensor([[10.,  2.,  3.],
        [ 4.,  5.,  6.]])

In [122]:
x_stack = torch.stack([x,x], dim=3)
x_stack

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

In [123]:
x.squeeze()

tensor([[10.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]])

In [124]:
x = torch.arange(0,10,1)

In [131]:
x, x.shape, x.size()

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]), torch.Size([10]))

In [133]:
x = x.reshape(1,10)
x, x.shape, x.size()

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([1, 10]),
 torch.Size([1, 10]))

In [142]:
z = x.squeeze()
z, z.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [145]:
z = z.unsqueeze(1)

z, z.shape

(tensor([[[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]]), torch.Size([1, 1, 1, 10]))

In [153]:
img = torch.rand([224,224,3])
img[0][0][0] = 45
img, img.shape

(tensor([[[4.5000e+01, 5.0926e-01, 4.8375e-01],
          [4.7024e-01, 1.5501e-01, 6.7726e-01],
          [3.0258e-02, 3.7678e-01, 4.0339e-01],
          ...,
          [6.8244e-01, 4.9364e-01, 7.2182e-01],
          [5.6145e-01, 4.1936e-01, 2.9934e-01],
          [3.1550e-01, 9.9866e-01, 9.3458e-01]],
 
         [[2.9427e-01, 6.4098e-01, 1.7061e-01],
          [3.0839e-02, 1.9525e-01, 3.6514e-01],
          [1.0226e-01, 7.3235e-01, 8.9888e-01],
          ...,
          [1.0129e-01, 1.6587e-01, 5.0351e-01],
          [6.9887e-01, 8.9994e-01, 2.1496e-01],
          [4.6410e-01, 2.2066e-01, 3.0147e-02]],
 
         [[3.0162e-01, 9.7419e-01, 8.6423e-01],
          [5.8284e-02, 7.1122e-01, 3.5277e-01],
          [9.7247e-02, 3.4496e-01, 1.9088e-01],
          ...,
          [2.0130e-01, 7.0651e-01, 1.3481e-01],
          [8.8429e-01, 5.2855e-01, 4.8978e-02],
          [1.7256e-01, 1.9774e-01, 9.6253e-01]],
 
         ...,
 
         [[1.5551e-01, 1.3928e-01, 5.9167e-01],
          [6.7002e

In [154]:
img.permute(2,0,1)
img.shape

torch.Size([224, 224, 3])

In [155]:
img

tensor([[[4.5000e+01, 5.0926e-01, 4.8375e-01],
         [4.7024e-01, 1.5501e-01, 6.7726e-01],
         [3.0258e-02, 3.7678e-01, 4.0339e-01],
         ...,
         [6.8244e-01, 4.9364e-01, 7.2182e-01],
         [5.6145e-01, 4.1936e-01, 2.9934e-01],
         [3.1550e-01, 9.9866e-01, 9.3458e-01]],

        [[2.9427e-01, 6.4098e-01, 1.7061e-01],
         [3.0839e-02, 1.9525e-01, 3.6514e-01],
         [1.0226e-01, 7.3235e-01, 8.9888e-01],
         ...,
         [1.0129e-01, 1.6587e-01, 5.0351e-01],
         [6.9887e-01, 8.9994e-01, 2.1496e-01],
         [4.6410e-01, 2.2066e-01, 3.0147e-02]],

        [[3.0162e-01, 9.7419e-01, 8.6423e-01],
         [5.8284e-02, 7.1122e-01, 3.5277e-01],
         [9.7247e-02, 3.4496e-01, 1.9088e-01],
         ...,
         [2.0130e-01, 7.0651e-01, 1.3481e-01],
         [8.8429e-01, 5.2855e-01, 4.8978e-02],
         [1.7256e-01, 1.9774e-01, 9.6253e-01]],

        ...,

        [[1.5551e-01, 1.3928e-01, 5.9167e-01],
         [6.7002e-01, 4.0245e-01, 4.7231e-01]

In [156]:
import numpy as np

In [157]:
arr = np.arange(1,10,1)

In [158]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
ten = torch.from_numpy(arr)

In [160]:
ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [161]:
torch.cuda.is_available()

True

In [162]:
!nvidia-smi

Wed Feb 28 20:04:02 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.61                 Driver Version: 551.61         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   62C    P2             52W /   60W |    1850MiB /   6144MiB |    100%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [163]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [164]:
device

'cuda'

In [170]:
tensor = torch.tensor([1,2,3])

In [173]:
tensor.device

device(type='cpu')

In [176]:
t_gpu = tensor.to(device)

In [177]:
tensor.device

device(type='cpu')

In [183]:
t_gpu.device

device(type='cuda', index=0)

In [180]:
t_gpu[2] = 4

In [181]:
t_gpu

tensor([1, 2, 4], device='cuda:0')

In [182]:
tensor = t_gpu.to("cpu")
tensor.device

device(type='cpu')

In [184]:
tensor = t_gpu.cpu()
tensor.device

device(type='cpu')