In [1]:
!nvidia-smi

Wed Jul 17 16:50:42 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   54C    P2             24W /   60W |    1527MiB /   6144MiB |     10%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

torch.__version__

'2.3.1+cu121'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[1]

tensor([3, 4])

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                         [2,3,4]]])

In [14]:
TENSOR


tensor([[[1, 2, 3],
         [2, 3, 4]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 2, 3])

In [17]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
RAND = torch.rand(3,4)
RAND

tensor([[0.7849, 0.7972, 0.1120, 0.6075],
        [0.5178, 0.0889, 0.3397, 0.2240],
        [0.1619, 0.9683, 0.1610, 0.3013]])

In [21]:
RAND.dtype

torch.float32

In [22]:
RAND = torch.rand(3,4, dtype=torch.float16)
RAND.dtype

torch.float16

In [23]:
RAND

tensor([[0.1104, 0.3755, 0.0498, 0.2212],
        [0.2681, 0.0913, 0.3037, 0.2129],
        [0.9395, 0.9570, 0.9590, 0.3696]], dtype=torch.float16)

In [24]:
TEST = torch.tensor([3,6,-1], dtype=torch.float16, device="cpu", requires_grad=False)

In [25]:
TEST

tensor([ 3.,  6., -1.], dtype=torch.float16)

In [26]:
TEST32 = TEST.type(torch.int)

In [27]:
TEST32

tensor([ 3,  6, -1], dtype=torch.int32)

In [28]:
TEST*TEST32

tensor([ 9., 36.,  1.], dtype=torch.float16)

In [29]:
TEST.dtype

torch.float16

In [30]:
TEST.shape

torch.Size([3])

In [31]:
TEST.ndim

1

In [32]:
TEST.device

device(type='cpu')

In [33]:
TEST.size()

torch.Size([3])

In [34]:
TEST / TEST32

tensor([1., 1., 1.], dtype=torch.float16)

In [35]:
TEST = torch.tensor([[1,2],[3,4]], dtype=torch.float16)
TEST32 = torch.tensor([[5,6]], dtype=torch.float16)

In [36]:
TEST32

tensor([[5., 6.]], dtype=torch.float16)

In [37]:
torch.mm(TEST, TEST32.T)

tensor([[17.],
        [39.]], dtype=torch.float16)

In [38]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

tensor_A * tensor_B

tensor([[ 7., 20.],
        [24., 44.],
        [45., 72.]])

In [39]:
tensor_A.min()

tensor(1.)

In [40]:
tensor_A.mean()

tensor(3.5000)

In [41]:
tensor_A.sum()

tensor(21.)

In [42]:
tensor_A.argmin()

tensor(0)

In [43]:
tensor_A.argmax()

tensor(5)

In [44]:
tensor_A[0][1]

tensor(2.)

In [45]:
tensor_A.size()

torch.Size([3, 2])

In [46]:
tensor_A_reshape = tensor_A.reshape(2,3)


In [47]:
tensor_A_reshape

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [48]:
x = tensor_A_reshape.view(3,2)

In [49]:
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [50]:
x[0][0] = 10


In [51]:
x

tensor([[10.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]])

In [52]:
tensor_A_reshape

tensor([[10.,  2.,  3.],
        [ 4.,  5.,  6.]])

In [53]:
# x_stack = torch.stack([x,x], dim=3)
# x_stack

In [54]:
x.squeeze()

tensor([[10.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]])

In [55]:
x = torch.arange(0,10,1)

In [56]:
x, x.shape, x.size()

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]), torch.Size([10]))

In [57]:
x = x.reshape(1,10)
x, x.shape, x.size()

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([1, 10]),
 torch.Size([1, 10]))

In [58]:
z = x.squeeze()
z, z.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [59]:
z = z.unsqueeze(1)

z, z.shape

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([10, 1]))

In [60]:
img = torch.rand([224,224,3])
img[0][0][0] = 45
img, img.shape

(tensor([[[4.5000e+01, 5.1826e-01, 9.0377e-02],
          [1.7748e-01, 1.9772e-01, 2.8403e-01],
          [5.5046e-01, 5.8719e-01, 5.5305e-01],
          ...,
          [1.0854e-01, 5.6748e-02, 4.9549e-01],
          [8.3931e-03, 7.1124e-01, 3.2960e-01],
          [7.0176e-01, 5.6898e-01, 7.3460e-01]],
 
         [[7.8194e-02, 1.0107e-01, 9.7666e-01],
          [5.1155e-01, 5.1274e-01, 9.3671e-02],
          [2.4074e-01, 8.9469e-01, 9.0270e-01],
          ...,
          [5.0073e-02, 9.8541e-01, 3.4882e-01],
          [1.8096e-01, 7.8235e-01, 6.9354e-01],
          [9.7097e-02, 4.1308e-01, 9.6494e-01]],
 
         [[4.4187e-01, 8.8683e-01, 4.0902e-01],
          [1.8175e-01, 7.8212e-01, 4.5489e-01],
          [6.7373e-01, 5.4927e-01, 2.5853e-01],
          ...,
          [6.3018e-01, 9.3059e-03, 9.9060e-01],
          [6.0863e-01, 6.7818e-01, 4.6705e-01],
          [5.9908e-01, 2.2197e-01, 4.0806e-01]],
 
         ...,
 
         [[5.8841e-01, 6.3878e-02, 3.3587e-01],
          [5.5101e

In [61]:
img.permute(2,0,1)
img.shape

torch.Size([224, 224, 3])

In [62]:
img

tensor([[[4.5000e+01, 5.1826e-01, 9.0377e-02],
         [1.7748e-01, 1.9772e-01, 2.8403e-01],
         [5.5046e-01, 5.8719e-01, 5.5305e-01],
         ...,
         [1.0854e-01, 5.6748e-02, 4.9549e-01],
         [8.3931e-03, 7.1124e-01, 3.2960e-01],
         [7.0176e-01, 5.6898e-01, 7.3460e-01]],

        [[7.8194e-02, 1.0107e-01, 9.7666e-01],
         [5.1155e-01, 5.1274e-01, 9.3671e-02],
         [2.4074e-01, 8.9469e-01, 9.0270e-01],
         ...,
         [5.0073e-02, 9.8541e-01, 3.4882e-01],
         [1.8096e-01, 7.8235e-01, 6.9354e-01],
         [9.7097e-02, 4.1308e-01, 9.6494e-01]],

        [[4.4187e-01, 8.8683e-01, 4.0902e-01],
         [1.8175e-01, 7.8212e-01, 4.5489e-01],
         [6.7373e-01, 5.4927e-01, 2.5853e-01],
         ...,
         [6.3018e-01, 9.3059e-03, 9.9060e-01],
         [6.0863e-01, 6.7818e-01, 4.6705e-01],
         [5.9908e-01, 2.2197e-01, 4.0806e-01]],

        ...,

        [[5.8841e-01, 6.3878e-02, 3.3587e-01],
         [5.5101e-02, 6.6811e-01, 6.3896e-01]

In [63]:
import numpy as np

In [64]:
arr = np.arange(1,10,1)

In [65]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
ten = torch.from_numpy(arr)

In [67]:
ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [68]:
torch.cuda.is_available()

True

In [69]:
!nvidia-smi

Wed Jul 17 16:50:54 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   54C    P8              9W /   60W |    1510MiB /   6144MiB |     29%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [70]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [71]:
device

'cuda'

In [72]:
tensor = torch.tensor([1,2,3])

In [73]:
tensor.device

device(type='cpu')

In [74]:
t_gpu = tensor.to(device)

In [75]:
tensor.device

device(type='cpu')

In [76]:
t_gpu.device

device(type='cuda', index=0)

In [77]:
t_gpu[2] = 4

In [78]:
t_gpu

tensor([1, 2, 4], device='cuda:0')

In [79]:
tensor = t_gpu.to("cpu")
tensor.device

device(type='cpu')

In [80]:
tensor = t_gpu.cpu()
tensor.device

device(type='cpu')

In [81]:
image = torch.rand(size=(224,224,3))

perm_image = image.permute((2,0,1))

print(image.shape, perm_image.shape)

torch.Size([224, 224, 3]) torch.Size([3, 224, 224])


In [82]:
print(perm_image[0,0,0])
image[0,0,0] = 10
print(image[0,0,0], perm_image[0,0,0])

tensor(0.5157)
tensor(10.) tensor(10.)


In [83]:
import torch
import numpy as np

In [88]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor, array.dtype, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 torch.float32)

In [89]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [90]:
tensor = torch.tensor([1,2,3], device='cuda')
tensor, tensor.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))